### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pbougue**
Just did a 'npm update'
Hoping it won't break anything, and solve possible vulnerabilities (at least one warning should be handled)

### CODE REVIEW

**Comment by nonifier** [comment]
> Hoping it won't break anything
Did you try locally ? Is there any test suite to run around the playground ?

**Comment by TeXitoi** [comment]
js-lint and code generation is tested on travis.

**Comment by TeXitoi** [comment]
these vulnerabilities are not really a thing as we use npm only for building, the app is handled by bower and the deps are much lower.

**Comment by pbougue** [comment]
Yep, anyway some are still pending, using `npm update` and maybe `npm audit` could help (but there might be some broken things, so I won't tackle it)

**Pull request merged**
