### PR TITLE
Add application patterns

### PR DESCRIPTION
**Pull request by azime**
Jira: [NAVP-1722](https://jira.kisio.org/browse/NAVP-1722)

Example:

image

### CODE REVIEW

**Review by xlqian — APPROVED** [review]

**Comment by TeXitoi** [comment]
I'd phrase that "18:00:00-20:21:00 on Thu,Fri between 2021-01-14 and 2021-01-15"

**Review by nonifier — APPROVED** [review]
Nice one !

**Comment by azime** [comment]
@TeXitoi I propose:
since 2021-01-14 until 2021-01-15 on Thu, Fri between 18:00:00-17:21:00 and 17:00:00-20:21:00 and  15:00:00-20:21:00

**Comment by TeXitoi** [comment]
Fine for me, except "in a or b or c" (not "between a and b and c")

**Comment by azime** [comment]
@TeXitoi ok for me

**Pull request merged**
