### PR TITLE
Change to stamen terrain tiles

### PR DESCRIPTION
**Pull request by TeXitoi**
To test: http://texitoi.eu/navitia-playground/play.html

What do you think?

### CODE REVIEW

**Comment by dvdn** [comment]
Hi, result is really nice from a 'human' point of view,
but IMO not 'Public transport' oriented enough

**Comment by TeXitoi** [comment]
@dvdn current tiles are not so public transport oriented either.

@sbouchy prefers the actual tiles.

**Comment by xlqian** [comment]
with this tile, I think public transport lines are much less marked than the current one...

**Comment by TeXitoi** [comment]
OK, no one like it. I close.

Thanks for your feedbacks!

**Pull request closed without merging**
