### PR TITLE
add access points into journeys

### PR DESCRIPTION
**Pull request by xlqian**
Access Points are now displayed in the sections' summaries:

image

Access Points are alose displayed when drawing the whole journey on the map

image

A new object is added to the section's extension
image

image

### CODE REVIEW

**Comment by TeXitoi** [comment]
Wouldn't it be better to have something between the access and the stop point? Like that, it's quite disturbing.

**Comment by xlqian** [comment]
image

**Comment by TeXitoi** [comment]
That's the purple of the feature field? perfect.

**Comment by TeXitoi** [comment]
But it should be the same parameters as the walking dots, with white under, no?

**Comment by xlqian** [comment]
but I want a kind of new color different from the purple which used by crowfly

**Comment by xlqian** [comment]
let me try something new

**Comment by xlqian** [comment]
let me try something new

**Comment by TeXitoi** [comment]
more spaced dots?

**Comment by xlqian** [comment]
It would be great if I could be able to use the color of the public transit

**Comment by xlqian** [comment]
image

**Review by TeXitoi — APPROVED** [review]

**Comment by TeXitoi** [comment]
Mmm, metro-marker has it's metro transparent, should be white

**Comment by xlqian** [comment]
@TeXitoi  Entrance Exit have now their own icons!! 

image

**Comment by TeXitoi** [comment]
When will we have this nice feature on https://api.navitia.io/v1/coverage/fr-idf/journeys ?

**Comment by xlqian** [comment]
@TeXitoi the new features can be activated by using  `_access_points=true`, but I think right now the data is not yet updated...

**Pull request merged**
